name: Build and Deploy to Azure Container Services

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'


      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ secrets.AZURE_REGISTRY_NAME }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io/myapp:${{ github.sha }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name ${{ secrets.AZURE_CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --image ${{ env.IMAGE_NAME }}
